trigger:
- main

pool:
  name: 'Autobots'

variables:
  AZURE_DEVOPS_PAT: $(System.AccessToken)

stages:
- stage: Build
  jobs:
  - job: BuildProject
    pool:
      name: 'Autobots'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
    - script: |
        dotnet build --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Build Project'
    - script: |
        dir $(Build.ArtifactStagingDirectory)
      displayName: 'List Build Artifacts'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
