import pandas as pd
from ortools.linear_solver import pywraplp

# Load the test priority data generated by Q-learning
df = pd.read_csv("CosmosDB/scheduled_tests_qlearning.csv")

# Define scheduling parameters
MAX_TOTAL_TIME = 20  # in seconds (adjust as needed)

# Initialize solver
solver = pywraplp.Solver.CreateSolver("SCIP")

# Define binary decision variables for each test case
x = {}
for i, row in df.iterrows():
    x[i] = solver.IntVar(0, 1, f"x_{i}")

# Constraint: total duration of selected tests must be within time budget
solver.Add(solver.Sum(x[i] * row["avgTime"] for i, row in df.iterrows()) <= MAX_TOTAL_TIME)

# Objective: maximize the total Q value (priority score from Q-learning)
solver.Maximize(solver.Sum(x[i] * row["Q_value"] for i, row in df.iterrows()))

# Solve the optimization problem
status = solver.Solve()

# Output results
if status == pywraplp.Solver.OPTIMAL:
    print("✅ Optimal test schedule found!\n")
    selected = df[[x[i].solution_value() > 0.5 for i in df.index]]

    print(f"\n📌 Selected {len(selected)} out of {len(df)} test cases.")
    print(selected[["testCaseId", "testCaseTitle", "Q_value", "avgTime"]])
    print(f"\n⏱ Total Scheduled Time: {selected['avgTime'].sum():.2f} sec")
    print(f"⭐ Total Q Value: {selected['Q_value'].sum():.4f}")

    # Save selected schedule
    selected.to_csv("CosmosDB/scheduled_tests_qlearning_solved.csv", index=False)
    print("📁 Saved selected tests to CosmosDB/scheduled_tests_qlearning_solved.csv")
else:
    print("❌ No optimal solution found.")
